# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: dlru
        timeout-minutes: 120
        run: |
          C:
          cd /
          md zdxvv
          md zdxvvdl
          cd zdxvvdl
          Invoke-WebRequest -Uri https://cdn01.doax-venusvacation.jp/production/patch_data/app/ver.04.00.00/APP004000000000_70da0fef.exe -OutFile APP004000000000_70da0fef.exe
          Invoke-WebRequest -Uri https://github.com/Klanly/stevs2019/releases/download/3.0/KT.reg -OutFile KT.reg
          reg import KT.reg
          dir
          C:\zdxvvdl\APP004000000000_70da0fef.exe
          
          
          
      - name: ziping
        if: always()
        run: 7z a C:\v2019c.7z "C:\zdxvv" -mqs -ms=on
          
      - name: uploadexe
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: exacu
          path: C:\v2019c.7z
          
          
     
