# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
         

      
           
      #Invoke-WebRequest -Uri "https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-windows-x86_64.exe" -OutFile bazel.exe
          
      - name: Install dependencies
        run: |
          pip3 install six numpy wheel keras_applications keras_preprocessing opt_einsum pandas protobuf wrapt gast==0.3.3 --no-deps
          pip3 install six numpy --no-deps
          C:
          cd /
          md tfmake
          cd tfmake
          git clone --branch r1.14 https://github.com/tensorflow/tensorflow.git c:\tfmake\tf14
          cd tf14
          Invoke-WebRequest -Uri https://github.com/Klanly/bleeda/releases/download/1.02/tf114.zip -OutFile tf114.zip
          7z e tf114.zip -aoa
          dir
          
          
        env:
          USE_BAZEL_VERSION: 2.0.0
          BAZEL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          BAZEL_VC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
          PYTHON_DIRECTORY: c:\hostedtoolcache\windows\python\3.7.9\x64
          BAZEL_SH: C:\Program Files\Git\bin\bash.exe
          

      - name: runbash
        run: |
          cd c:\tfmake\tf14
          bazelisk build
        #shell: bash
        #run: c:/tfmake/tf14/tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh
        
        env:
          USE_BAZEL_VERSION: 2.0.0
          BAZEL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          BAZEL_VC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
          PYTHON_DIRECTORY: hostedtoolcache\windows\python\3.7.9\x64
          BAZEL_SH: C:\Program Files\Git\bin\bash.exe
          
          
      - name: ziping
        if: always()
        run: 7z a C:\tfbb.7z "c:\tfmake" -mqs -ms=on
          
      - name: uploadexe
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: finaa
          path: C:\tfbb.7z
          
          
     
