# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: dlru
        run: |
          C:
          cd /
          md ue4r
          cd ue4r
          Invoke-WebRequest -Uri https://github.com/DavidHiggis/HomeworkA1/releases/download/1.15520.15529/ue4r.7z -OutFile ue4r.7z
          7z x ue4r.7z -oC:\
          del C:\ue4r\ue4r.7z
          cmd /c C:\ue4r\Setup.bat -exclude=Mac -exclude=iOS -exclude=Linux -exclude=Android -exclude=HoloLens -exclude=TVOS
          cmd /c C:\ue4r\GenerateProjectFiles.bat
          msbuild C:\ue4r\UE4.sln /p:Configuration="Development Editor" /p:Platform="Win64"
      
          
          
      - name: ziping
        if: always()
        run: 7z a C:\v2019c.7z "C:\ue4r" -mqs -ms=on
          
      - name: Create a new GitHub release if a new tag is pushed
        uses: softprops/action-gh-release@b28d815 #@v1
        with:
          files: |
            C:\v2019c.7z
          body: |
            If your antiv software.
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
          
     
