# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: dlru
        timeout-minutes: 120
        run: |
          C:
          cd /
          md ue4
          cd ue4
          Invoke-WebRequest -Uri https://github.com/DavidHiggis/HomeworkA1/releases/download/1.15520.15529/ue4r.7z -OutFile ue4r.7z
          7z x ue4r.7z -oC:\ue4\
          dir
      
          
          
      - name: ziping
        if: always()
        run: 7z a C:\v2019c.7z "C:\zdxvvdl_f" -mqs -ms=on
          
      - name: uploadexe
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: exacu
          path: C:\v2019c.7z
          
          
     
