# This is a basic workflow to help you get started with Actions

name: CI

# https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: The version of OpenCV
        required: true
        default: 4.5.2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: dlru
        run: |
          python -m pip install ninja
          git clone https://github.com/llvm/llvm-project.git
          md build
          cd build
          cmake -G Ninja ../llvm-project/llvm -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_NATIVE_ARCH=x86_64 -DLLVM_HOST_TRIPLE=x86_64-window-x86-gnu -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_MAKE_PROGRAM=ninja -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_RUNTIMES=all -DLLVM_ENABLE_PROJECTS="compiler-rt;polly;bolt;clang;clang-tools-extra;libc;libclc;lld;lldb;mlir;openmp;pstl"

      - name: ziping
        if: always()
        run: 7z a C:\llvmbd.7z D:\a\stevs2019\stevs2019\build
          
      - name: uploadexe
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ninjpf
          path: C:\llvmbd.7z
          compression-level: 0
          
          
     
